### ISSUE TITLE
publish plugin to maven repo

### ISSUE THREAD

**Issue by kwonglau** [eventuate-foundation/eventuate-plugins-gradle#10]
not able to build any project depending on this plugin because bintray is no long working

**Comment by cer** [comment]
Please be more specific: which project? Which branch?

**Comment by kwonglau** [comment]
eventuate-common-messaging

* What went wrong:
A problem occurred configuring root project 'eventuate-common-messaging'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve io.eventuate.plugins.gradle:eventuate-plugins-gradle-versions:0.10.0.BUILD-SNAPSHOT.
     Required by:
         project :
      > Could not resolve io.eventuate.plugins.gradle:eventuate-plugins-gradle-versions:0.10.0.BUILD-SNAPSHOT.
         > Unable to load Maven meta-data from https://dl.bintray.com/eventuateio-oss/eventuate-maven-release/io/eventuate/plugins/gradle/eventuate-plugins-gradle-versions/0.10.0.BUILD-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/eventuateio-oss/eventuate-maven-release/io/eventuate/plugins/gradle/eventuate-plugins-gradle-versions/0.10.0.BUILD-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/eventuateio-oss/eventuate-maven-release/io/eventuate/plugins/gradle/eventuate-plugins-gradle-versions/0.10.0.BUILD-SNAPSHOT/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
   > Could not resolve io.eventuate.plugins.gradle:eventuate-plugins-gradle-publish:0.10.0.BUILD-SNAPSHOT.
     Required by:
         project :
      > Could not resolve io.eventuate.plugins.gradle:eventuate-plugins-gradle-publish:0.10.0.BUILD-SNAPSHOT.
         > Unable to load Maven meta-data from https://dl.bintray.com/eventuateio-oss/eventuate-maven-release/io/eventuate/plugins/gradle/eventuate-plugins-gradle-publish/0.10.0.BUILD-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/eventuateio-oss/eventuate-maven-release/io/eventuate/plugins/gradle/eventuate-plugins-gradle-publish/0.10.0.BUILD-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/eventuateio-oss/eventuate-maven-release/io/eventuate/plugins/gradle/eventuate-plugins-gradle-publish/0.10.0.BUILD-SNAPSHOT/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by kwonglau** [comment]
same error for the following projects on master branch
eventuate-messaging-activemq
eventuate-messaging-kafka
eventuate-messaging-rabbitmq
eventuate-messaging-redis
eventuate-cdc

**Comment by cer** [comment]
The problem (at least in the eventuate-common-messaging repo) is that the SNAPSHOT dependency is in https://snapshots.repositories.eventuate.io/repository.

However,  https://dl.bintray.com/eventuateio-oss/eventuate-maven-release is listed before that repo, which causes this failure.

```
diff --git gradle.properties gradle.properties
index 5248ec6..4bad7e7 100644
--- gradle.properties
+++ gradle.properties
@@ -5,7 +5,7 @@ bintrayRepoType=defineMe
 bintrayPkgName=eventuate-common-messaging
 bintrayPkgVcsUrl=https://github.com/eventuate-foundation/eventuate-common-messaging
 
-eventuateMavenRepoUrl=file:///Users/cer/.m2/testdeploy,https://dl.bintray.com/eventuateio-oss/eventuate-maven-release,https://snapshots.repositories.eventuate.io/repository
+eventuateMavenRepoUrl=file:///Users/cer/.m2/testdeploy,https://snapshots.repositories.eventuate.io/repository
 
 eventuateUtilVersion=0.14.0.BUILD-SNAPSHOT
 

```

**Comment by kwonglau** [comment]
I see. Thanks for the quick reply

**Comment by cer** [comment]
I'm running a script that removes references to dl.bintray.com from all the repositories.

**Comment by kwonglau** [comment]
thankyou
